// Generated by axtp-gen. Do not edit manually.
#pragma once
#include <cstdint>

namespace axtp {

enum class PayloadType : std::uint8_t {
    Control = 0x01,
};

enum class ControlOpcode : std::uint8_t {
    Connect = 0x01,
};

enum class RpcEncoding : std::uint8_t {
    Binary = 0x02,
};

enum class RpcOp : std::uint8_t {
    Request = 0x01,
};

enum class MethodId : std::uint16_t {
    BrightnessSet = 0x0602,
};

enum class EventId : std::uint16_t {
    BrightnessChanged = 0x8601,
};

enum class ErrorCode : std::uint16_t {
    Success = 0x0000,
};

enum class CapabilityId : std::uint16_t {
    BrightnessSet = 0x0602,
    BrightnessEvent = 0x0603,
};

} // namespace axtp
